defaults: &defaults
  summary_file: wiki.json
  root_parent: ROOT
  data_path: <%= "#{Rails.root}/db/wiki" %>
  image_path: <%= "#{Rails.root}/public/images" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
